### ISSUE TITLE
[Feature Request] - Add team member names to support queue list

### ISSUE THREAD

**Issue by MelindaMalmgren** [AmericanAirlines/Hangar#115]
### Pre-requisites:
- [x] I looked through both [open and closed issues](../issues?utf8=✓&q=is%3Aissue) and did not find another request for the same or similar feature.

## Describe the solution you'd like
As a staff member it would be ideal to be able to see who is waiting in the queue so that we can tell people how far down the list they are.

**Comment by SpencerKaiser** [comment]
@MelindaMalmgren I know it's been super long since you opened this, but was this just essentially having team member names next to their team name in the queue? I just updated the title; let me know if that's accurate.

**Comment by MelindaMalmgren** [comment]
@SpencerKaiser I think this was so that when someone comes up to us and asks where they are in the queue we would be able to tell them. It's been so long since I've seen how we handle this that I'm not sure beyond that. Right now all we have is the ability to get the next person, right?

**Comment by SpencerKaiser** [comment]
Yea I believe that's correct. Perfect, I'll make sure this gets addressed for 2.0 😁

**Comment by SpencerKaiser** [comment]
Closing in favor of #159
