### ISSUE TITLE
[Feature Request] - Enforce 'strict' flag for Typescript

### ISSUE THREAD

**Issue by SpencerKaiser** [AmericanAirlines/Hangar#116]
### Pre-requisites:
- [x] I looked through both [open and closed issues](../issues?utf8=✓&q=is%3Aissue) and did not find another request for the same or similar feature.

## Describe the solution you'd like

We should enable `strict` mode in `tsconfig.json` and correct all the errors that come up.

**Comment by smitshah2531** [comment]
Joseph and I are taking care of this issue!
