### ISSUE TITLE
[Feature Request] - Refactor Slack handlers

### ISSUE THREAD

**Issue by SpencerKaiser** [AmericanAirlines/Hangar#129]
### Pre-requisites:
- [x] I looked through both [open and closed issues](../issues?utf8=✓&q=is%3Aissue) and did not find another request for the same or similar feature.

## Is your feature request related to a problem, or an open issue? Describe the problem, and if applicable, reference the issue.

Our existing implementation of Slack handlers is brittle and very difficult to test.

## Describe the solution you'd like

Refactor Slack handlers to follow the paradigm implemented in [Asking for a Friend](https://github.com/AmericanAirlines/AskingForAFriend).

**Comment by oscargoddard** [comment]
Can you explain more on what is needed on this issue?

**Comment by SpencerKaiser** [comment]
@oscargoddard I'm implementing this (I'm assigned to the issue and `help wanted` was removed)

The gist is that the pattern for registering Slack handlers can be improved based on a new model I created, so I want to refactor the app to use that pattern. I'm actually digging into it this morning, so hopefully I'll have a PR up by the end of the day if you're still curious.
