### ISSUE TITLE
[Feature Request] - Start ngrok tunnel during dev

### ISSUE THREAD

**Issue by johnkahn** [AmericanAirlines/Hangar#133]
### Pre-requisites:
- [x] I looked through both [open and closed issues](../issues?utf8=✓&q=is%3Aissue) and did not find another request for the same or similar feature.

## Is your feature request related to a problem, or an open issue? Describe the problem, and if applicable, reference the issue.

When someone is starting the project locally, it should auto start ngrok and print the url. There should be a way to configure parts of it using environment (auth token, subdomain, etc)

## Additional context
Use the ngrok library (already in dev dependencies) 
https://github.com/bubenshchykov/ngrok

**Comment by SpencerKaiser** [comment]
Moving this back into the backlog. This might be a great bit of functionality to add, but we'd need to find a way to prevent the tunnel from being re-created inadvertently since it'll generate a new URL that the Slack App will need to be updated with.

**Comment by johnkahn** [comment]
More effort than it's worth
