### ISSUE TITLE
[Feature Request] - Create API route to return all support items

### ISSUE THREAD

**Issue by SpencerKaiser** [AmericanAirlines/Hangar#158]
### Pre-requisites:
- [x] I looked through both [open and closed issues](../issues?utf8=✓&q=is%3Aissue) and did not find another request for the same or similar feature.

## Is your feature request related to a problem, or an open issue? Describe the problem, and if applicable, reference the issue.

We need a new endpoint to allow an admin to retrieve all support items from the UI

## Describe the solution you'd like

Create a new route nested within `api/supportRequest/` for `getAll`, which should return a list of all support request items. The method should default to only returning `Pending` items, however, a query parameter of `status` should be utilized to provide others if needed (list of values in `entities/supportRequest.ts`).

**Comment by Ulfingrad** [comment]
Maha and I will be taking this one.

**Comment by msiddique933** [comment]
Austin and I pushed a commit with no verify issue158
