### ISSUE TITLE
[Feature Request] - Add functionality to respond with helpful information if tagged in a public channel

### ISSUE THREAD

**Issue by SpencerKaiser** [AmericanAirlines/Hangar#16]
### Pre-requisites:
- [x] I looked through both [open and closed issues](../issues?utf8=✓&q=is%3Aissue) and did not find another request for the same or similar feature.

## Describe the solution you'd like

If the bot is tagged in a public channel, it should respond in a thread with some info about how to use the bot. 

If possible, include a button that opens the DM with the bot.

**Comment by oscargoddard** [comment]
I am working on this

**Comment by TheDivexz** [comment]
I'm also working on it along with Osman
