### ISSUE TITLE
[Feature Request] - Move listing and checkstyle to a new Linting Workflow

### ISSUE THREAD

**Issue by SpencerKaiser** [AmericanAirlines/Hangar#160]
### Pre-requisites:
- [x] I looked through both [open and closed issues](../issues?utf8=✓&q=is%3Aissue) and did not find another request for the same or similar feature.

## Is your feature request related to a problem, or an open issue? Describe the problem, and if applicable, reference the issue.

We should improve our build time by removing `npm run lint` and `npm run checkstyle` from our build Workflow

## Describe the solution you'd like

Make a new Workflow called `linting.yml` which should execute the above commands along with any necessary commands to prep the environment (`npm ci`)

**Comment by oscargoddard** [comment]
Can you please provide more explanation on what should be done?

**Comment by SpencerKaiser** [comment]
I think the description above is sufficient. Those two listing tasks need to be removed from the build workflow and moved to a new workflow. Do you have a specific question about part of that?

**Comment by oscargoddard** [comment]
We were discussing about how to test these changes. That might be my specific question

**Comment by SpencerKaiser** [comment]
You can execute the actions in your fork. If you need to test, you can simply change `main` to the branch you're on and they should execute.

The end result of the action should be executing `npm run lint` and `npm run checkstyle`. If an error is thrown in either, it should fail the action.
