### ISSUE TITLE
[Feature Request] - Create config dashboard component (view only)

### ISSUE THREAD

**Issue by SpencerKaiser** [AmericanAirlines/Hangar#174]
### Pre-requisites:
- [x] I looked through both [open and closed issues](../issues?utf8=✓&q=is%3Aissue) and did not find another request for the same or similar feature.

## Is your feature request related to a problem, or an open issue? Describe the problem, and if applicable, reference the issue.

The UI dashboard for admins should be updated to include a new component which retrieves all config items from the DB and displays them.

## Describe the solution you'd like

A new component on the dashboard should...
- List all config items
- Refresh the items on a recurring basis (every 10s)

**Comment by Peruggia29** [comment]
@smitshah2531 and I will take this issue.

**Comment by Peruggia29** [comment]
@SpencerKaiser @johnkahn Regarding modifying the text box, are they just going to modify true or false within the value?

**Comment by SpencerKaiser** [comment]
The current implementation is that a configuration item's value is a string, so it could be anything. That being said, most of the time it'll be true/false so you're welcome to get fancy with it if you want.
