### ISSUE TITLE
[Feature Request] - Create supportRequest remind endpoint

### ISSUE THREAD

**Issue by SpencerKaiser** [AmericanAirlines/Hangar#175]
### Pre-requisites:
- [x] I looked through both [open and closed issues](../issues?utf8=✓&q=is%3Aissue) and did not find another request for the same or similar feature.

## Is your feature request related to a problem, or an open issue? Describe the problem, and if applicable, reference the issue.

We need a new endpoint to remind users who have not come to start their support session

## Describe the solution you'd like

After popping a user off the queue, a support user/admin should be able to "remind the user" to head over for their support session. To support this, we need to create `/api/supportRequest/remindUser` which will accept a `supportRequestId` and a `relativeTimeElapsedString` (similar to `/abandonRequest`; use that as an example) and will need to utilize `messageUsers` to send a reminder to them. The reminder text should include the amount of time elapsed.

**Comment by Ulfingrad** [comment]
Maha and I will take care of this issue.
