### ISSUE TITLE
[Feature Request] - Refactor supportRequest `getNext` endpoint to allow type specification

### ISSUE THREAD

**Issue by SpencerKaiser** [AmericanAirlines/Hangar#176]
### Pre-requisites:
- [x] I looked through both [open and closed issues](../issues?utf8=✓&q=is%3Aissue) and did not find another request for the same or similar feature.

## Is your feature request related to a problem, or an open issue? Describe the problem, and if applicable, reference the issue.

In order to support a front-end change to allow users to get specific types of support requests, we need to modify `api/supportRequest/getNext` to allow for a type specification

## Describe the solution you'd like

The endpoint above should be update to include a new, optional query parameter, `type`. In addition, the `getNextSupportRequest` helper method in `entities/supportRequest.ts` should be updated to accept an optional type to use within its query.

**Comment by SpencerKaiser** [comment]
Closing in favor of another issue which will allow users to pop specific requests from the queue

**Comment by johnkahn** [comment]
Closed on accident

**Comment by Ulfingrad** [comment]
Joseph and I will take care of this issue
