### ISSUE TITLE
[Feature Request] - Create new "Coming Soon" GitHub Pages site

### ISSUE THREAD

**Issue by SpencerKaiser** [AmericanAirlines/Hangar#177]
### Pre-requisites:
- [x] I looked through both [open and closed issues](../issues?utf8=✓&q=is%3Aissue) and did not find another request for the same or similar feature.

## Is your feature request related to a problem, or an open issue? Describe the problem, and if applicable, reference the issue.

We should create a new user-friendly docs site to help non-technical people get Hangar up and running (e.g., a non-customized version of Hangar without coding changes incorporated).

## Describe the solution you'd like

We should set up a "Coming Soon" pages site which has simple branding and a message saying the site contents are coming soon. We should utilize [Docsify](https://docsify.js.org/#/) for our docs site engine.

**Comment by oscargoddard** [comment]
We can take care of this issue
