### ISSUE TITLE
[Feature Request] - Create endpoint for handling a support request

### ISSUE THREAD

**Issue by SpencerKaiser** [AmericanAirlines/Hangar#179]
### Pre-requisites:
- [x] I looked through both [open and closed issues](../issues?utf8=✓&q=is%3Aissue) and did not find another request for the same or similar feature.

## Is your feature request related to a problem, or an open issue? Describe the problem, and if applicable, reference the issue.

Our frontend user should be able to serve a _specific_ support request instead of getting the next of any type.

## Describe the solution you'd like

Create a new api endpoint for `PATCH` - `api/supportRequest/` which accepts a supportRequest id as part of the body and then marks that support request as being `inProgress`. This functionality should mirror what is taking place in `getNext` but should operate on a specific support request.

**Comment by Ulfingrad** [comment]
Maha and I will be taking on this issue.
