### ISSUE TITLE
[Bug] - Typo in bot thread response

### ISSUE THREAD

**Issue by SpencerKaiser** [AmericanAirlines/Hangar#187]
### Pre-requisites:
- [x] I looked through both [open and closed issues](../issues?utf8=✓&q=is%3Aissue) and did not find an existing bug.

## Description

When the bot responds to a public @mention, there's a typo in the response

## Expected Behavior

Typo-free text

## Actual Behavior

`choose` is misspelled (`chose`) and the text ends with an extraneous ` character

## Steps to Reproduce

Tag @hangar in a public channel and observe the response:
>Hey there :wave: I can help your team during the hackathon! To see all of the things I can help with, simply click/tap my name and **chose** 'Go to App' :tada:**`**

**Comment by SpencerKaiser** [comment]
@oscargoddard @TheDivexz FYI 👆

**Comment by oscargoddard** [comment]
I will take care of it
