### ISSUE TITLE
[Feature Request] - Create Support Request Page

### ISSUE THREAD

**Issue by SpencerKaiser** [AmericanAirlines/Hangar#196]
### Pre-requisites:
- [x] I looked through both [open and closed issues](../issues?utf8=✓&q=is%3Aissue) and did not find another request for the same or similar feature.

## Is your feature request related to a problem, or an open issue? Describe the problem, and if applicable, reference the issue.

We need to make the support experience even cleaner and make the UI more functional

## Describe the solution you'd like

The existing support request UI items should be moved to a new `/support/[secret]` route which will allow users to navigate to a specific support-request page. The secret in the URL should be pulled from the environment variable `SUPPORT_SECRET`

Note: You'll need to move all the user name field (at the top of the page) and logic over as well

**Comment by msiddique933** [comment]
Dhruv and I will take this issue as well

**Comment by SpencerKaiser** [comment]
If yall want to go above and beyond, you're welcome to take this on and get it finished by Tues, but the main expectation was that you finish existing PRs. Totally up to yall 😄

**Comment by oscargoddard** [comment]
I talked with @msiddique933 and @TheDivexz.
