### ISSUE TITLE
[Feature Request] - Creating a Bug Report Button on the UI Page(s)

### ISSUE THREAD

**Issue by Ulfingrad** [AmericanAirlines/Hangar#198]
### Pre-requisites:
- [x] I looked through both [open and closed issues](../issues?utf8=✓&q=is%3Aissue) and did not find another request for the same or similar feature.

## Is your feature request related to a problem, or an open issue? Describe the problem, and if applicable, reference the issue.

This is an Epic for the creation of a bug reporting system. Users should be able to simply press a button and type out a bug report if they stumble across one while judging, handling support requests, etc.

## Describe the solution you'd like

The user should be able to press a button that either sends them to a separate bug report page or gives them a prompt on the current page. In either of these situations, the user will describe the bug and how to reproduce it if possible. The user will then be able to press a button to submit the bug's details. 

I assume we will then want to have a database that stores all of these submissions for further review by the hackathon host. The hackathon sponsor should be able to pull up all of these database entries on a page for review. It is possible that some of these bugs come from features that the sponsor has added, so they can fix/disregard bugs relating to their own features. However, if the sponsor stumbles upon bugs that they are not responsible for (aka our fault), they should be able to send the issues to us by being able to specify the bug reports in the database by id and then clicking a button in order to send them to us.

From this point, I am unsure how we want to handle the bugs and issues sent to us. I know we were talking about somehow hooking them up to Github, but am not completely sure how we would accomplish this. My best guess would be to store all issues sent to us and then either we would manually go through them and decide if they are worthy of an issue on Github, or we can have some sort of automated issue generator that will create issues if there are enough similar submissions (I don't know how we would accomplish this in a timely manner, but it seems like a cool idea at the very least).

## Describe alternatives you've considered

We could have a bug submission button on a single page, or we could put it on every page the users will have access to. We also probably don't need a page that shows all of the pug reports as one could just look in the database, but I think it would make things cleaner to look at.

## Additional context

The front-end portion of this epic may have to wait until the UI overhaul is completed as it would be pointless to add a bug report button to the current UI and then repurpose it later down the line.

**Comment by SpencerKaiser** [comment]
@AmericanAirlines/hangar-maintainers I think we should modify this one to simply redirect the user to a new issue with the bug template: https://github.com/AmericanAirlines/Hangar/issues/new?assignees=&labels=bug&template=bug_report.md&title=%5BBug%5D+-+YOUR_TITLE_HERE

Thoughts?

cc @dre8597

**Comment by SpencerKaiser** [comment]
Proposed Issue:

Add a new footer to the frontend which includes a reference to Hangar being an open source project, includes a GitHub icon which links to the repo, and includes buttons for `Report a bug` and `Suggest a feature` which take the user to one of our repo's issue templates
