### ISSUE TITLE
[Feature Request] - String Dictionary 

### ISSUE THREAD

**Issue by TheDivexz** [AmericanAirlines/Hangar#202]
### Pre-requisites:
- [x] I looked through both [open and closed issues](../issues?utf8=✓&q=is%3Aissue) and did not find another request for the same or similar feature.

## Is your feature request related to a problem, or an open issue? Describe the problem, and if applicable, reference the issue.

We want to pull out the strings that users read from the code and store them in a String Dictionary so when text is supposed to shown to the  user, the dictionary is referenced and the appropriate text is displayed. This way it is easier to customize the text that is displayed to the user and potentially adds the option to have support for multiple languages

## Describe the solution you'd like

Create a string dictionary that contain keys which stores text to be displayed and when text is to be show to the user, one of these keys is referenced instead

```typescript
export const stringDictionary: Record<string, string | (params: Record<string, string>) => string> = {}

/* TEAM FORMATION */
stringDictionary.teamRegistrationSuccess = (params) => `You have registered your team for sponsor judging. Our team will stop by during judging to see your hack. Best of luck and see you soon!\n**Team Name**: ${params.teamName}\n**Table Number**: ${params.tableNumber}\n**Project Description**: ${params.projectDescription}`
```

## Describe alternatives you've considered

An alternate was to just have string variables 

## Additional context

if we want to port this slack bot to discord then this feature is essential 
working with @oscargoddard

**Comment by oscargoddard** [comment]
Discord Markdown

Bold: **[TEXT]**
Italics: *[TEXT]* or _[TEXT]_
Underscore: __[TEXT]__
Strikethrough: ~~Strikethrough~~
Code: `[TEXT]`
Hyperlink: [Hyperlink!]([URL])
Remove embeds: <[URL]>
