### ISSUE TITLE
[Spike] - Research Getting Challenge Information on Discord

### ISSUE THREAD

**Issue by smitshah2531** [AmericanAirlines/Hangar#205]
### Pre-requisites:
- [x] I looked through both [open and closed issues](../issues?utf8=✓&q=is%3Aissue) and did not find another request for the same or similar feature.

## Is your feature request related to a problem or an open issue? Describe the problem, and if applicable, reference the issue.

We gotta figure out how to implement the ability to get challenge information in Discord.

## Describe the solution you'd like

Study up on ways to implement the ability to get challenge information with a command from the bot. However this is implemented, this will definitely involve interacting with the [https://discord.com/developers/docs/intro](https://discord.com/developers/docs/intro) (Discord API), so that’s probably a good place to start.

## Describe alternatives you've considered

There are a few ways this can be done, so look into what could work and the best option out of the choices!

## Additional context

I will be working with @Ulfingrad

**Comment by Ulfingrad** [comment]
The solution we found involves Discord.js, which makes interacting with the Discord API a lot easier compared to if we were messing with it straight-up. First, we create a client, and then the bot waits for a specific message in any channel in the Discord server. Once the bot detects a specific message (in our case !ChallengeInformation), the bot DMs the hackathon information URL (located in the .env file) to the user. Additionally, the bot needs to log in, which is accomplished by referencing the bot's token (Which will also be located in the .env file).

Additionally, we are thinking of adding a couple of features to the bot on top of this barebones implementation. The first of these features is the bot posting a message in the respective channel upon a user entering the!ChallengeInformation command. This message simply says that the user has been sent a DM.

The second feature we were thinking of adding was to autodelete the command messages after a certain amount of time. This would include all messages involved in the Discord channels (but not the message DMed to the user).

The last feature we were thinking of adding is limiting the scope of the command in regard to specific text channels. This means that the command could work in one channel, but not in other channels.
