### ISSUE TITLE
[Spike] - Research Team Formation in Discord (Commands/Link)

### ISSUE THREAD

**Issue by msiddique933** [AmericanAirlines/Hangar#209]
### Pre-requisites:
- [x] I looked through both [open and closed issues](../issues?utf8=✓&q=is%3Aissue) and did not find another request for the same or similar feature.

## Is your feature request related to a problem, or an open issue? Describe the problem, and if applicable, reference the issue.

We need to figure out how we can implement team formation in Discord.

## Describe the solution you'd like

We want to implement commands to make it easier to pull information while using discord for a hackathon.

## Describe alternatives you've considered

Here is a website describing all commands on discord: [https://just-some-bots.github.io/MusicBot/using/commands/](https://just-some-bots.github.io/MusicBot/using/commands/)

## Additional context

Worked on this issue with @smitshah2531 

@msiddique933 and @Peruggia29 are going to work on this

**Comment by Peruggia29** [comment]
I'll join Maha for this issue

**Comment by SpencerKaiser** [comment]
Pending questions:
- Are there modals/dialogs that can be opened?
  - If not, do we just chain messages together?
    **- If so, is there some sort of metadata we can leverage within the request to keep track of where we are in a flow?**
- Do we need to update the user table to maintain a context of where they're at in a given flow?
