### ISSUE TITLE
[Feature Request] - Joining queue to pitch your idea

### ISSUE THREAD

**Issue by msiddique933** [AmericanAirlines/Hangar#211]
### Pre-requisites:
- [x] I looked through both [open and closed issues](../issues?utf8=✓&q=is%3Aissue) and did not find another request for the same or similar feature.

## Is your feature request related to a problem, or an open issue? Describe the problem, and if applicable, reference the issue.

We want a space where people can give suggestions or ideas to better the Discord server.

## Describe the solution you'd like

Create a Queue bot to add suggestions.

## Describe alternatives you've considered

Here is a link to create a queue bot : [https://top.gg/bot/679018301543677959](https://top.gg/bot/679018301543677959)

## Additional context

Related to #212

**Comment by johnkahn** [comment]
This should handle

* Intake of initial questions
* Ready messages
* Remind messages
* Cancellation messages

**Comment by Ulfingrad** [comment]
@smitshah2531 and I will be looking into this issue!
