### ISSUE TITLE
[Feature Request] - Technical Help in Discord

### ISSUE THREAD

**Issue by oscargoddard** [AmericanAirlines/Hangar#212]
### Pre-requisites:
- [X] I looked through both [open and closed issues](../issues?utf8=✓&q=is%3Aissue) and did not find another request for the same or similar feature.

## Is your feature request related to a problem, or an open issue? Describe the problem, and if applicable, reference the issue.

Create the functionality in Discord that enables users to join to the Tech Support Queue. This functionality already exists on Slack bot Home screen as interactive buttons. We need to find a method of implementation to allow users to join to the support queue since Discord bot doesn't have a home screen. 

## Describe the solution you'd like

If the command is tagged "!getHelp" in any of the channels bot should be responding with the confirmation text and add the user to the support queue. 

## Describe alternatives you've considered

Support channel can be added to the Discord server to implement this same functionality. 

## Additional context

We will work with @TheDivexz on this issue. 

Related to #211

**Comment by johnkahn** [comment]
This should handle

* Intake of initial questions
* Ready messages
* Remind messages
* Cancellation messages

Should work the same was as #211
