### ISSUE TITLE
[Feature Request] - Common Interface API

### ISSUE THREAD

**Issue by johnkahn** [AmericanAirlines/Hangar#214]
### Pre-requisites:
- [x] I looked through both [open and closed issues](../issues?utf8=✓&q=is%3Aissue) and did not find another request for the same or similar feature.

## Describe the problem
We want to be able to add new platforms to the bot without having to rewrite the logic layer for it

## Describe the solution you'd like
A common module API that defines abstracted methods that translate into the platform specific logic. Adding a new platform should be as easy as extending a class and overriding the methods that the platform supports.

## Describe alternatives you've considered
Writing code for each platform in the logic with a bunch of `if/else` statements 🤢 

## Functionality to Implement
- A helper method to determine which platform is active. Example pseudocode:
``` typescript
// src/common.ts (or whatever you choose)
// Determine which env vars are present, throw an error if NEITHER or BOTH are supplied
export enum SupportedPlatform {
slack: 'Slack';
discord: 'Discord'
}

export const activePlatform = isSlackActive ? SupportedPlatform.slack : SupportedPlatform.discord;
```
- A single `messageUsers` method (`/src/api/utils/messageUser.ts`) which utilizes the `activePlatform` to figure out which platform util methods should be used

Once implemented, the API should be updated with the new `messageUsers` method. The startup of the app should only try to instantiate a single app (Discord OR Slack) and error should be thrown if NEITHER or BOTH are supplied.

**Comment by SpencerKaiser** [comment]
@johnkahn as part of this issue, we should figure out a good way of disabling the unused platform (e.g., if we're using Discord, the Slack app shouldn't start and vice versa)

**Comment by johnkahn** [comment]
Got an app spun up really easily for [Discord.js](https://discord.js.org/#/docs/main/stable/general/welcome) and it's got great typescript support.

I think it'll probably be the fastest way to get it working
