### ISSUE TITLE
[Spike] - Discord SDK/App Creation

### ISSUE THREAD

**Issue by SpencerKaiser** [AmericanAirlines/Hangar#215]
### Pre-requisites:
- [x] I looked through both [open and closed issues](../issues?utf8=✓&q=is%3Aissue) and did not find another request for the same or similar feature.

## Is your feature request related to a problem, or an open issue? Describe the problem, and if applicable, reference the issue.

We need to research the best way to create a new app for Discord

## Describe the solution you'd like

Research the potential SDKs we can use and select one as the approach we're going with

**Comment by johnkahn** [comment]
https://github.com/discordjs/discord.js
