### ISSUE TITLE
[Bug] - Eslint is not checking tsx files

### ISSUE THREAD

**Issue by SpencerKaiser** [AmericanAirlines/Hangar#217]
### Pre-requisites:
- [x] I looked through both [open and closed issues](../issues?utf8=✓&q=is%3Aissue) and did not find an existing bug.

## Description

Our implementation of prettier is ignoring tsx files

## Expected Behavior

All relevant code should be linted

## Actual Behavior

The files are not being linted

## Steps to Reproduce

Make a change to a tsx file that should throw an eslint warning/error and then look at the code within VSCode (with the eslint plugin enabled)

**Comment by oscargoddard** [comment]
There is a documentation and possible solution on this issue at the following link. https://www.robertcooper.me/using-eslint-and-prettier-in-a-typescript-project
