### ISSUE TITLE
[CHORE] - Create Command bot

### ISSUE THREAD

**Issue by msiddique933** [AmericanAirlines/Hangar#218]
### Pre-requisites:
- [x] I looked through both [open and closed issues](../issues?utf8=✓&q=is%3Aissue) and did not find another request for the same or similar feature.

## Is your feature request related to a problem, or an open issue? Describe the problem, and if applicable, reference the issue.

Related to 210, 209

## Describe the solution you'd like

Creating a bot to implement the commands on discord

## Describe alternatives you've considered

Here is a link to create bot [https://discordpy.readthedocs.io/en/latest/discord.html](https://discordpy.readthedocs.io/en/latest/discord.html)

## Additional context

working with @Peruggia29

**Comment by oscargoddard** [comment]
I think we can close this Issue since the implementation already concluded and we have a bot

**Comment by johnkahn** [comment]
Already implemented
