### ISSUE TITLE
[Feature Request] - Remove SQLite in tests

### ISSUE THREAD

**Issue by johnkahn** [AmericanAirlines/Hangar#231]
### Pre-requisites:
- [x] I looked through both [open and closed issues](../issues?utf8=✓&q=is%3Aissue) and did not find another request for the same or similar feature.

## Is your feature request related to a problem, or an open issue? Describe the problem, and if applicable, reference the issue.
We have to bend over backwards to get our production code working in the test environment with SQLite.

## Describe the solution you'd like
* Remove SQLite from tests.
* Create a mock `BaseEntity` that all the mocked `Entity` classes can use. This will setup the common mocks for `save`, `findOne`, etc. Then create a mock file for each that correctly mock out static/instance methods that are specific to that class. Then call `jest.mock()` on each entity in the setup 
* Change all instances of `simple-json` to `json`. (Along with any enums, arrays, and etc SQLite can't do natively)

## Describe alternatives you've considered
S̸͙̓Ṷ̵̗̝̼͒͆͌F̸̱͉͙͌̒F̵̫̀̑͋Ȩ̷̭̓̊͒̎R̸͈̾͠

## Additional context

<img src="https://user-images.githubusercontent.com/7807353/101080625-a2dd0300-356e-11eb-8ab3-713180eab598.png" width="300" />

**Comment by SpencerKaiser** [comment]
Already fixed by #319
