### ISSUE TITLE
[Feature Request] - Add section to README for environment variables

### ISSUE THREAD

**Issue by johnkahn** [AmericanAirlines/Hangar#263]
### Pre-requisites:
- [x] I looked through both [open and closed issues](../issues?utf8=✓&q=is%3Aissue) and did not find another request for the same or similar feature.

## Is your feature request related to a problem, or an open issue? Describe the problem, and if applicable, reference the issue.
The README has some information scattered through different sections about environment variables, but we should have a dedicated section about them and how they work.

## Describe the solution you'd like

Create a new section for environment variables and how to set them up

## Describe alternatives you've considered

Be vague and mean to new contributors 😩

**Comment by allysonmking** [comment]
will work on this with Olin!
