### ISSUE TITLE
[Feature Request] - Fix Dependency Vulnerabilities

### ISSUE THREAD

**Issue by Ulfingrad** [AmericanAirlines/Hangar#264]
### Pre-requisites:
- [x] I looked through both [open and closed issues](../issues?utf8=✓&q=is%3Aissue) and did not find another request for the same or similar feature.

## Is your feature request related to a problem, or an open issue? Describe the problem, and if applicable, reference the issue.

Uh-oh, there's a lot of high-risk vulnerabilities relating to our dependencies! We should probably fix those...

## Describe the solution you'd like

Update our dependencies so that the majority of the vulnerabilities are gone.

**Comment by johnkahn** [comment]
Working on this

**Comment by johnkahn** [comment]
Not working on this

**Comment by turnerlevey** [comment]
Natalie and I can work on this

**Comment by johnkahn** [comment]
You can run `npm audit` to see the vulnerabilities, and you can use `npm audit fix` to auto-fix the easy ones. There will probably be some more though that will require you to manually update packages. The easiest way to do that is to look in the `package.json` for the packages that have vulnerabilities and then look at their page on https://www.npmjs.com for the latest version, then change the version number to the latest on listed. After updating `package.json` with the new version run `npm install` to get the latest.

As long as `npm test` passes and you can still run the app then this is done 👍
