### ISSUE TITLE
[Feature Request] - Discord command aliases

### ISSUE THREAD

**Issue by SpencerKaiser** [AmericanAirlines/Hangar#285]
### Pre-requisites:
- [x] I looked through both [open and closed issues](../issues?utf8=✓&q=is%3Aissue) and did not find another request for the same or similar feature.

## Describe the solution you'd like

All of our Discord commands should have simple, easy to use aliases (e.g., `!technicalSupport` could be `!ts`)

**Comment by SpencerKaiser** [comment]
Suggested regex: `/^!(technicalSupport|ts)$/i`

**Comment by johnkahn** [comment]
@RazvanPreotu99 Just noticed that this wasn't closed, when your PR closes multiple issue, the word closes needs to precede every issue number.

Example: `Closes #123 and Closes #1234`
