### ISSUE TITLE
[Feature Request] - Add documentation for GitHub Secrets

### ISSUE THREAD

**Issue by SpencerKaiser** [AmericanAirlines/Hangar#32]
### Pre-requisites:
- [x] I looked through both [open and closed issues](../issues?utf8=✓&q=is%3Aissue) and did not find another request for the same or similar feature.

## Describe the solution you'd like

This project utilizes GitHub secrets but there isn't a description of what secrets should be added or where to generate them. A section should be added to the README with suggested and required secrets and where to generate each.

As part of this issue, add a new section to the CI/CD part of the readme to document Codecov (do some research and set it up for your own fork of this project).

**Comment by Ulfingrad** [comment]
Maha and I were planning on taking care of this issue.
