### ISSUE TITLE
[Enhancement] - Better README walkthrough

### ISSUE THREAD

**Issue by tristengeven** [AmericanAirlines/Hangar#329]
### Pre-requisites:
- [x] I looked through both [open and closed issues](../issues?utf8=✓&q=is%3Aissue) and did not find another request for the same or similar feature.

## Describe the solution you'd like

Comb over the README and better tune the instructions to lead a lesser-technical person through the initial installation steps to launch the app. This could include GIF/video tutorial components.

## Additional context

We should probably make these updates to our [GitHub Pages site](https://americanairlines.github.io/Hangar/) because that is the ideal path for a non-technical Hangar user.

**Comment by johnkahn** [comment]
If there are any gifs/videos created put them in a summary/description block so they are hidden by default.

https://gist.github.com/jbsulli/03df3cdce94ee97937ebda0ffef28287
