### ISSUE TITLE
[Feature Request] - Allow new user to start app without slack/discord configuration

### ISSUE THREAD

**Issue by tristengeven** [AmericanAirlines/Hangar#330]
### Pre-requisites:
- [x] I looked through both [open and closed issues](../issues?utf8=✓&q=is%3Aissue) and did not find another request for the same or similar feature.

## Describe the solution you'd like

When the user hits the home page, if there is no admin secret or no platform, then redirect to `/setup`

**Comment by SpencerKaiser** [comment]
@tristengeven FYI, I modified the description a bit. Let me know if you have questions or if you disagree with what I modified it to be.
