### ISSUE TITLE
[Feature Request] - Create Setup Page UI

### ISSUE THREAD

**Issue by tristengeven** [AmericanAirlines/Hangar#331]
### Pre-requisites:
- [x] I looked through both [open and closed issues](../issues?utf8=✓&q=is%3Aissue) and did not find another request for the same or similar feature.

## Describe the solution you'd like

Navigate the user through setting up a slack or discord app. Ask for necessary values. Ask for config items. Wait for the user to submit. Show ‘loading’ icon while app saves the values to the Config items, to give users a ‘seamless build’ feel.

**Comment by SpencerKaiser** [comment]
@tristengeven I removed the reference to Mac/Windows; although that's a necessary component of local development, the goal of this should be for a production instance of the app. We should still continue to document the Mac/Windows differences, but the front end experience shouldn't get into those topics.

**Comment by johnkahn** [comment]
I edited the description to remove the overriding .env variables and restarting the app to instead save those to the config table. So there should probably be another issue created to move all .env variables that won't be there on initial deploy (slack/discord tokens, secrets, etc) to the Config table. And then this story would be dependent on that one.
