### ISSUE TITLE
[Feature Request] - Config Setup Api

### ISSUE THREAD

**Issue by tristengeven** [AmericanAirlines/Hangar#332]
### Pre-requisites:
- [x] I looked through both [open and closed issues](../issues?utf8=✓&q=is%3Aissue) and did not find another request for the same or similar feature.

## Is your feature request related to a problem, or an open issue? Describe the problem, and if applicable, reference the issue.

Done in parallel with #331 

## Describe the solution you'd like

Because of changes implemented since the conception of this issue, the scope of work is now defined as creating the api through which the setup page will assign initial configItem values. This functionality should include ADD/MODIFY for adminSecret, discordChannelIds, discordBotToken, slackBotToken, & slackSigningSecret.

**Comment by johnkahn** [comment]
I'm not 100% sure we need this anymore. I think after #331 is done that this will automatically be done because everything is in the database there is no need to back it up or have any errors because of frontend validation.

**Comment by tristengeven** [comment]
I intend to use this as the issue to track the api development for adding/modifying config items.
