### ISSUE TITLE
Create nav bar and default pages

### ISSUE THREAD

**Issue by SpencerKaiser** [AmericanAirlines/Hangar#384]
### Pre-requisites:
- [x] I looked through both [open and closed issues](../issues?utf8=✓&q=is%3Aissue) and did not find another request for the same or similar feature.

## Description

Create a nav bar and blank pages for the following:
- My Project - `/app/project` 
- Get Help - `/app/help` 
- Work at American - `/work-at-american`

The nav element should include an SVG for the Hangar logo using the [Hangar font](https://fonts.google.com/specimen/Pacifico?query=paci&preview.text=Hangar&preview.text_type=custom)
- John to make the SVG(s)

**Comment by maxwell-tchiabe** [comment]
hello i would like to work on this issue

**Comment by SpencerKaiser** [comment]
@maxwell-tchiabe you're welcome to work on any of these issues, but as a heads up, we're prepping for a hackathon in two weeks and will be knocking these issues out rather quickly. If you plan to work on something, give us a heads up and start in on it immediately - if we don't have a pull request up for it within a reasonable amount of time after your comment (hours, not days), we'll need to work on it ourselves in order to hit our deadline.

After the event, this repo will become much more stable and we won't be as pressed for time, so it should be a better experience for external contributors 😉 

Please let me know if there's anything specific I can help with or if there's any feedback that might make things easy for you; we'd love to have you as a contributor!

**Comment by maxwell-tchiabe** [comment]
thank you for the quick reply, I have already started since yesterday to work on it

**Comment by maxwell-tchiabe** [comment]
can you help me?
I can not run the app local
in which directory or file should I put the navbar?

**Comment by SpencerKaiser** [comment]
@maxwell-tchiabe have you read through the README in detail? That's a super important file that specifies exactly how to run the app and get things working locally. Please read through it and follow every step it specifies; if you still have trouble after going through that, open up a new issue with specified details about error messages/missing docs/etc. that would help 😄 

For this issue specifically, @johnkahn is working on it today and will have something finished by EOD tomorrow, so I'd say get the app running locally, get comfortable with the codebase, and then find an issue you can work on. Once you find something, comment with clarification questions if anything is unclear!
