### ISSUE TITLE
SPIKE: Notifications

### ISSUE THREAD

**Issue by SpencerKaiser** [AmericanAirlines/Hangar#392]
### Pre-requisites:
- [x] I looked through both [open and closed issues](../issues?utf8=✓&q=is%3Aissue) and did not find another request for the same or similar feature.

## Description

We need to research how to notify users via browser notifications AND via Discord notifications

- For browser notifications, do we have control over when we ask?
- For Discord notifications, can we _**start**_ DMs or do we need to have an existing message from the user first?
- Do we need any information other than what we get from the auth process? (#381)

**Comment by dre8597** [comment]
Discord Notifications:

-  From the [docs](https://discord.com/developers/docs/resources/user#create-dm), no prior conversation needs to be established prior to the bot sending a DM.
- We only need the user's id, which is provided by the Discord auth process.
- There's a 50 requests/sec global rate limit for any bot action and individual rate limits for individual requests (Which aren't specified).

**Comment by dre8597** [comment]
Browser Notifications:

- Users are prompted upon entry to the site and doesn't ask again once answered. (User can enable/disable them by clicking on the lock icon next to URL in the address bar)
- We can use [web-push](https://github.com/web-push-libs/web-push) to handle the push service for sending each notification
- User entity will need to be updated to save a list of generated subscription links for each user agent mobile/web browser
- Example of a fully-working [app](https://github.com/Spyna/push-notification-demo) with push notification service (with MIT License)
