### ISSUE TITLE
Work at American page

### ISSUE THREAD

**Issue by SpencerKaiser** [AmericanAirlines/Hangar#400]
### Pre-requisites:
- [x] I looked through both [open and closed issues](../issues?utf8=✓&q=is%3Aissue) and did not find another request for the same or similar feature.

## Description

Create a new page that details information about internships and the ADEPT program
- Include component listing cool tech/projects
- List perks/benefits
- Show Skyview pics

The header should also include a component which lets them "Come chat with us" with a button for `Join Queue`
- If unauthenticated, take the user through auth and add a `joinQueue=true` query parameter - after redirect, trigger the joinQueue functionality
- If in the queue, retrieve the position via `/api/queue/chat` (#396)

**Comment by michael20148205** [comment]
Fovo
