### ISSUE TITLE
Admin Dashboard

### ISSUE THREAD

**Issue by SpencerKaiser** [AmericanAirlines/Hangar#414]
### Pre-requisites:
- [x] I looked through both [open and closed issues](../issues?utf8=✓&q=is%3Aissue) and did not find another request for the same or similar feature.

## Description

We need a new page which is only accessible to admins which displays all `AppConfig` items (dependent on #398) and lets them create/edit as needed. UI elements should correlate to their types

**Comment by johnkahn** [comment]
Also have a way to send messages to subscribed users
