### ISSUE TITLE
[Feature Request] - Create page for the retrieval of final judging results

### ISSUE THREAD

**Issue by SpencerKaiser** [AmericanAirlines/Hangar#45]
### Pre-requisites:
- [x] I looked through both [open and closed issues](../issues?utf8=✓&q=is%3Aissue) and did not find another request for the same or similar feature.

## Describe the solution you'd like

The app should include a page which can be used to view judging results.

~An endpoint should be created to allow for the retrieval of final judging results. The endpoint should retrieve and display judging results.~

**Comment by johnkahn** [comment]
Working on this
