### ISSUE TITLE
[Feature Request] - Move test and code coverage to standalone action

### ISSUE THREAD

**Issue by SpencerKaiser** [AmericanAirlines/Hangar#51]
### Pre-requisites:
- [x] I looked through both [open and closed issues](../issues?utf8=✓&q=is%3Aissue) and did not find another request for the same or similar feature.

## Describe the solution you'd like

Move `npm run test:coverage` and the codecov upload to a standalone action for transparency purposes. Without this change, it won't be clear if the build action failed due to an issue with the code or because of tests/coverage.

**Comment by MelindaMalmgren** [comment]
I'll take this one, it will give me a chance to get my feet wet with actions
