### ISSUE TITLE
[Feature Request] - Remove duplicate Actions

### ISSUE THREAD

**Issue by SpencerKaiser** [AmericanAirlines/Hangar#55]
### Pre-requisites:
- [x] I looked through both [open and closed issues](../issues?utf8=✓&q=is%3Aissue) and did not find another request for the same or similar feature.

## Describe the solution you'd like

After GitHub updates Actions to allow for branch-specific badges, we should:
- Remove the `PR-Build` action and update the `Build` action to trigger for PRs against the `main` branch
- Update the `README` with the appropriate `Build` badge and add a new badge for `Test` status

**Comment by TheDivexz** [comment]
me and @oscargoddard are taking this issue

**Comment by SpencerKaiser** [comment]
@TheDivexz make sure yall also do #160 since these two issues are bundled

**Comment by oscargoddard** [comment]
Can you please provide more explanation on what should be done?

**Comment by SpencerKaiser** [comment]
You'll need to research a bit, but we need the action to trigger on both `push` and `pull_request` against `main`

**Comment by SpencerKaiser** [comment]
Just updated the original description to use `main` as that's our default branch now
