### ISSUE TITLE
[Feature Request] - Create remind functionality for support queue

### ISSUE THREAD

**Issue by SpencerKaiser** [AmericanAirlines/Hangar#74]
### Pre-requisites:
- [x] I looked through both [open and closed issues](../issues?utf8=✓&q=is%3Aissue) and did not find another request for the same or similar feature.

## Describe the solution you'd like

If the user who requested help doesn't show up after being notified, the sponsor team should be able to send a reminder notification to them via the front end by clicking a `Remind` button which will utilize `/api/supportRequest/remindUser`

Dependent on #175

**Comment by Peruggia29** [comment]
@Ulfingrad are y'all grabbing this since its related to #175?

**Comment by Ulfingrad** [comment]
@Peruggia29 yup, although I already finished it yesterday (Just need to send in a PR for it)
