### ISSUE TITLE
[Bug] - Registration failing on iOS

### ISSUE THREAD

**Issue by johnkahn** [AmericanAirlines/Hangar#81]
### Pre-requisites:
- [x] I looked through both [open and closed issues](../issues?utf8=✓&q=is%3Aissue) and did not find an existing bug.

## Description
Registration does not seem to work on iOS

## Expected Behavior

It should work the same as other platforms

## Actual Behavior

Users are having issues on iOS

## Steps to Reproduce

Try to register on iOS

**Comment by SpencerKaiser** [comment]
I was able to reproduce this; the `teamMembers` view submission field is an empty array when sent from desktop, but not present when sent from mobile 🙄 working on a fix now
