### ISSUE TITLE
[Bug] - Page crashes when trying to get next when no support items exist

### ISSUE THREAD

**Issue by SpencerKaiser** [AmericanAirlines/Hangar#97]
### Pre-requisites:
- [x] I looked through both [open and closed issues](../issues?utf8=✓&q=is%3Aissue) and did not find an existing bug.

## Description

If you click get next when no items are available, the page throws an error

## Expected Behavior

The page displays that no requests are available

## Actual Behavior

The page throws and error and becomes unresponsive

## Steps to Reproduce

Load the homepage and hit the get next button with no items in the queue

**Comment by SpencerKaiser** [comment]
@johnkahn wasn't this fixed already?

**Comment by Ulfingrad** [comment]
Maha and I were also planning on taking care of this issue.
